# Generated by Django 5.1.6 on 2025-04-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='measure',
            field=models.CharField(default='units', max_length=100),
        ),
    ]
