# Generated by Django 5.1.6 on 2025-04-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transportbooking_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='commodity',
            field=models.CharField(default='productname', max_length=100),
        ),
    ]
