# Generated by Django 5.1.6 on 2025-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transportbooking_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportbooking',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
